repo_id,repo_full_name,file,file_sha1,match
366529600,m4udSec/Cacti-CVE-2020-8813,README.md,04f9a4f2b17e21e094da12f8653bc072eb6314e4,CVE-2020-8813
366529600,m4udSec/Cacti-CVE-2020-8813,cacti_rce.py.old,30c6a9725efadb46d2ea959ac7ced11a0584972f,CVE-2020-8813
366529600,m4udSec/Cacti-CVE-2020-8813,cacti_rce.py,ba2a345f929f3a5ce7ef32b59c1115a0fa52d049,CVE-2020-8813
366529600,m4udSec/Cacti-CVE-2020-8813,_GITHUB_REPO_METADATA_,,CVE-2020-8813
