repo_id,repo_full_name,file,file_sha1,match
346166714,electronforce/py2to3,CVE-2018-17057.py,21d3553be584ec8816705444b4ae7df7a7fda35b,CVE-2018-17057
346166714,electronforce/py2to3,README.md,8331876f345602d215b95ef29b9ef3b8ba939432,CVE-2018-17057
346166714,electronforce/py2to3,README.md,8331876f345602d215b95ef29b9ef3b8ba939432,CVE-2020-25213
346166714,electronforce/py2to3,CVE-2020-25213.py,bea105692aa3438db27ca3a7c0b2a0093cd4fc05,CVE-2020-25213
