repo_id,repo_full_name,file,file_sha1,match
412400011,knqyf263/CVE-2021-3129,attacker/exploit.py,08aa826da45d04d0ddeb43ccf0c201a7af6aba88,CVE-2021-3129
412400011,knqyf263/CVE-2021-3129,README.md,32527b575c8191c9317e713a93219284a264f726,CVE-2021-3129
412400011,knqyf263/CVE-2021-3129,_GITHUB_REPO_METADATA_,,CVE-2021-3129
