repo_id,repo_full_name,file,file_sha1,match
304755825,0xeb-bp/cve-2020-16898,README.md,0f8495af8bfd2aff248aff2836056baa53ca11c5,CVE-2020-16898
304755825,0xeb-bp/cve-2020-16898,crash.py,87d7b456debe83d46d13cdba8910b64830763dbc,CVE-2020-16898
304755825,0xeb-bp/cve-2020-16898,_GITHUB_REPO_METADATA_,,CVE-2020-16898
