repo_id,repo_full_name,file,file_sha1,match
263382958,I-Runtime-Error/CVE-2020-1938,CVE-2020-1938.pdf,9fb0f5d84b85b5c5785aabea8c1d513d18d9635f,CVE-2020-1938
263382958,I-Runtime-Error/CVE-2020-1938,_GITHUB_REPO_METADATA_,,CVE-2020-1938
